use_frameworks!
platform :ios, '10.0'

target 'DoraKit_Example' do
  pod 'DoraKit', :path => '../'
  
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'

  target 'DoraKit_Tests' do
    inherit! :search_paths

    
  end
end
